# Generated by Django 3.2.12 on 2022-04-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_folloings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='folloings',
            new_name='followings',
        ),
    ]
